### ISSUE TITLE
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 

### ISSUE THREAD

**Issue by roninby** [cloudfoundry/cf-deployment#189]
Hello,

I'm testing the well-known demo java app - [cities ](http://pcf-ford-workshop.cfapps.io/2016/03/15/lab--build-and-deploy-apps-on-pcf/) on a small local CF environment without external LB. Two apps including **cities-ui** and **cities-service** are now running.

```
[gcps@ansiblehost cities-ui]$ cf apps
Getting apps in org gcps / space gcps-dev as admin...
OK

name             requested state   instances   memory   disk   urls
spring-music     started           1/1         512M     1G     spring-music-insulting-minibus.cf.gcps.lab
cities-service   started           1/1         1G       1G     cities-service.cf.gcps.lab
cities-ui        started           1/1         1G       1G     cities-ui.cf.gcps.lab
[gcps@ansiblehost cities-ui]$ cf services
Getting services in org gcps / space gcps-dev as admin...
OK

name        service         plan   bound apps       last operation
cities-db   p-mysql         20mb   cities-service   create succeeded
cities-ws   user-provided          cities-ui
[gcps@ansiblehost cities-ui]$ bosh2 -e bosh-1 vms
Using environment '10.10.0.6' as client 'admin'

Task 179. Done

Deployment 'cf-1'

Instance                                          Process State  AZ  IPs         VM CID                                   VM Type
api/f23a31d0-7e89-45a7-b460-20b9aa573e3d          running        z1  10.11.0.19  vm-d5f4d2ed-caa9-4f85-987c-3c742cda2189  xlarge
blobstore/87fca99e-9903-44da-bc5c-96775ffb9781    running        z1  10.11.0.18  vm-cc1526e1-1be0-4b69-a088-a952381de1be  large
cc-bridge/ad06fa6f-79e1-4645-952a-71bdc19c462f    running        z1  10.11.0.25  vm-fd8437cd-14b2-4224-8e41-ef292e50f00e  default
cc-clock/c3c5564d-1831-40ea-9b33-c3486ae5e64d     running        z1  10.11.0.24  vm-2891cef2-7f92-48c2-a638-14dfa4206188  large
cc-worker/71c098d4-e0a8-40a6-9ccb-18cdd2255fff    running        z1  10.11.0.20  vm-e073a618-8895-4542-b237-2d21d29cc514  default
consul/73921eea-994a-45cb-a424-cdefaa5b60ff       running        z1  10.11.0.11  vm-7435469c-d7da-47f0-a105-8146f6b57aa7  default
diego-api/b9654105-386e-4521-978f-2ac3a0dd2eb1    running        z1  10.11.0.16  vm-11dd8ddc-0c9d-4897-8997-72cd85ab731e  large
diego-brain/5f6e6cc3-03a5-4736-9b6b-618eb7f9e875  running        z1  10.11.0.22  vm-56e6948d-82fb-43cf-8699-629604c4d7d2  default
diego-cell/8854e3e1-e485-498e-9fea-a675c7810c9c   running        z1  10.11.0.23  vm-31417d01-570a-4a37-908e-4be53e7c3bc6  xlarge
doppler/23c3ff53-5678-4763-bd74-ec4aedab2b6a      running        z1  10.11.0.14  vm-c1e6c52e-0251-4816-824e-a9674a86e241  default
etcd/b442f0b4-3489-4338-aa75-8f30a3575fb9         running        z1  10.11.0.13  vm-0574f44e-5037-4de1-9bae-6da931840085  default
log-api/4f2ad5cc-f3a7-4a71-b12d-0f4c58d51a81      running        z1  10.11.0.26  vm-bbbe354f-2467-43f4-ade7-b7d5cde9577e  default
mysql/b400ed81-46f1-4cce-baa0-94ebd4f5c28b        running        z1  10.11.0.15  vm-bcf1a07f-faea-4fac-81c0-5f60dcb2e4a5  large
nats/202f7340-155a-4bf4-86bf-146fde0011e8         running        z1  10.11.0.12  vm-77b1f3cd-240a-4646-9956-9707d1428248  large
router/63947cf4-fd3c-45f6-8727-798805b1ce41       running        z1  10.11.0.21  vm-3079b1e6-48ed-43fe-81b6-ebf09f3866fc  default
uaa/b6e2759e-ab31-44e0-a08a-c5b1666752a9          running        z1  10.11.0.17  vm-4ed4edcb-0499-433c-8475-a7e7db586555  default

16 vms

Task 180. Done

Deployment 'mysql-1'

Instance                                         Process State  AZ  IPs         VM CID                                   VM Type
arbitrator/b90dddf4-ae07-4cf0-9489-c0974e80707f  running        z1  10.11.0.29  vm-4c15f59a-e152-4b49-921a-c8cc6266b235  default
broker/26fcd8e0-a401-4e1b-acac-f7aa3e6bfb11      running        z1  10.11.0.31  vm-5f2da7a2-41ca-44d4-9511-eb855b5953b4  large
mysql/01362872-4959-44df-b23a-87040c8c47cf       running        z1  10.11.0.28  vm-b661aac8-cf4e-49ee-8361-4088816399ec  large
mysql/62685ac2-8424-4404-ab39-8ec312eb5f76       running        z1  10.11.0.27  vm-2b2ace4c-411a-4830-a1be-778a5489194d  large
proxy/0febf712-6dc0-4e3e-bc8d-6903c1061b76       running        z1  10.11.0.30  vm-1cb1d230-5b38-4b0d-b033-71b802888280  default

5 vms

[gcps@ansiblehost cities-ui]$ cf security-groups
Getting security groups as admin...
OK

     name               organization   space   lifecycle
#0   dns                <all>          <all>   running
     dns                <all>          <all>   staging
#1   p-mysql-service    <all>          <all>   running
#2   public_networks    <all>          <all>   running
     public_networks    <all>          <all>   staging
#3   t-router-service   <all>          <all>   running

```

The problem is there's no data shown in the web page of cities-ui. 

![image](https://user-images.githubusercontent.com/10234085/28719615-214a8304-73dd-11e7-8ca2-546a9990a321.png)

Looks like it's a certification problem according to app logs. Is there any configuration to skip certification verification between cf apps?  

```

[gcps@ansiblehost cities-ui]$ cf logs cities-ui --recent
Retrieving logs for app cities-ui in org gcps / space gcps-dev as admin...

   2017-07-28T20:57:56.55+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
   2017-07-28T20:57:56.55+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
   2017-07-28T20:57:56.55+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
   2017-07-28T20:57:56.55+0800 [APP/PROC/WEB/0] OUT     at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
   2017-07-28T20:57:56.55+0800 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
   2017-07-28T20:57:56.55+0800 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
   2017-07-28T20:57:56.55+0800 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
   2017-07-28T20:57:56.55+0800 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2017-07-28T20:57:56.55+0800 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2017-07-28T20:57:56.55+0800 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2017-07-28T20:57:56.55+0800 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT 2017-07-28 12:57:57.818 ERROR 5 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is feign.RetryableException: error sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target executing GET https://cities-service.cf.gcps.lab/cities/search/nameContains?q=a&page=0&size=15] with root cause
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.validator.Validator.validate(Validator.java:260)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.security.FileWatchingX509ExtendedTrustManager.checkServerTrusted(FileWatchingX509ExtendedTrustManager.java:78)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.security.DelegatingX509ExtendedTrustManager$4.accept(DelegatingX509ExtendedTrustManager.java:78)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.security.DelegatingX509ExtendedTrustManager.with(DelegatingX509ExtendedTrustManager.java:143)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at org.cloudfoundry.security.DelegatingX509ExtendedTrustManager.checkServerTrusted(DelegatingX509ExtendedTrustManager.java:74)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
   2017-07-28T20:57:57.81+0800 [APP/PROC/WEB/0] OUT     at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at feign.Client$Default.convertResponse(Client.java:125)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at feign.Client$Default.execute(Client.java:68)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at feign.MethodHandler$SynchronousMethodHandler.executeAndDecode(MethodHandler.java:126)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at feign.MethodHandler$SynchronousMethodHandler.invoke(MethodHandler.java:105)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:87)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at com.sun.proxy.$Proxy51.findByNameContains(Unknown Source)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at com.example.cities.controller.CitiesController.search(CitiesController.java:29)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Method.invoke(Method.java:498)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:280)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:89)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2017-07-28T20:57:57.82+0800 [APP/PROC/WEB/0] OUT     at java.lang.Thread.run(Thread.java:748)
   2017-07-28T21:01:35.77+0800 [RTR/0] OUT cities-ui.cf.gcps.lab - [2017-07-28T13:01:35.713+0000] "GET /cities/search?name=a&page=0&size=15 HTTP/1.1" 500 0 438 "https://cities-ui.cf.gcps.lab/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "172.31.2.102:63332" "10.11.0.23:61004" x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:"1f77ec91-dabe-415a-51b0-94bd83b6ee2a" response_time:0.057837291 app_id:"d94a5944-e002-4175-822d-82d8e3c581bb" app_index:"0" x_b3_traceid:"1aad3ff111f02b42" x_b3_spanid:"1aad3ff111f02b42" x_b3_parentspanid:"-"
   2017-07-28T21:01:35.77+0800 [RTR/0] OUT
   2017-07-28T21:01:37.02+0800 [RTR/0] OUT cities-ui.cf.gcps.lab - [2017-07-28T13:01:36.987+0000] "GET /cities/search?name=a&page=0&size=15 HTTP/1.1" 500 0 438 "https://cities-ui.cf.gcps.lab/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "172.31.2.102:63332" "10.11.0.23:61004" x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:"c7fc2800-02e5-41d1-6a9e-0e572e5b29c9" response_time:0.040233062 app_id:"d94a5944-e002-4175-822d-82d8e3c581bb" app_index:"0" x_b3_traceid:"24995dbefda976db" x_b3_spanid:"24995dbefda976db" x_b3_parentspanid:"-"
   2017-07-28T21:01:37.02+0800 [RTR/0] OUT

```

Thanks in advance.

**Comment by dsabeti** [comment]
Hi @roninby,

Configuring an app to skip certificate verification can't be done at the deployment level -- it's app specific. For example, if you look at one of our test apps, you can see that the developer of the app [had to write specific code](https://github.com/cloudfoundry-samples/logging-route-service/blob/05219af52eb306d365a36a8c18bdc48de808ae83/main.go#L95-L97) to skip certificate verification, and [provide it's own interface](https://github.com/cloudfoundry-samples/logging-route-service/blob/05219af52eb306d365a36a8c18bdc48de808ae83/main.go#L32-L34) for configuring the app to skip verification.

I'd suggest asking in the GitHub repo for the `cities` app if there's a way to configure it to skip certificate verification.

**Comment by roninby** [comment]
@dsabeti ,

You are right. After double-check the demo instruction, I just modified the CUPS URI from "https" to "http" as below, then it works. 

```
cf update-user-provided-service cities-ws -p "citiesuri"
citiesuri> http://cities-service.cf.gcps.lab)
```
Thank for you help.

**Comment by dsabeti** [comment]
No problem, happy to help.  I'll close the issue, but feel free to re-open it if you need more help.
