### ISSUE TITLE
Unable to download package / buildpacks (local deployment)

### ISSUE THREAD

**Issue by fadedreamz** [cloudfoundry/cf-deployment#276]
The local cf instance fails to download buildpack when pushing the application (it also failed to download the packages for deployement).

Following is the log for application upload -

```
Connected, dumping recent logs for app sample2 in org tse / space lab as admin...

2017-10-12T12:46:53.10-0400 [API/0]      OUT Created app with guid 78878f04-d36d-4df4-a9e4-b213d70d13f5
2017-10-12T12:46:53.63-0400 [API/0]      OUT Updated app with guid 78878f04-d36d-4df4-a9e4-b213d70d13f5 ({"route"=>"67c78de4-349c-4218-86b1-e1b0cddc0dd4", :verb=>"add", :relation=>"routes", :related_guid=>"67c78de4-349c-4218-86b1-e1b0cddc0dd4"})
2017-10-12T12:46:54.04-0400 [API/0]      OUT Uploading bits for app with guid 78878f04-d36d-4df4-a9e4-b213d70d13f5
2017-10-12T12:46:59.57-0400 [API/0]      OUT Creating build for app with guid 78878f04-d36d-4df4-a9e4-b213d70d13f5
2017-10-12T12:46:59.80-0400 [API/0]      OUT Updated app with guid 78878f04-d36d-4df4-a9e4-b213d70d13f5 ({"state"=>"STARTED"})
2017-10-12T12:46:59.88-0400 [STG/0]      OUT Downloading php_buildpack...
2017-10-12T12:46:59.90-0400 [STG/0]      OUT Downloaded php_buildpack
2017-10-12T12:46:59.92-0400 [STG/0]      OUT Creating container
2017-10-12T12:47:00.23-0400 [STG/0]      OUT Successfully created container
2017-10-12T12:47:00.23-0400 [STG/0]      OUT Downloading app package...
2017-10-12T12:47:00.31-0400 [STG/0]      OUT Downloaded app package (466.7K)
2017-10-12T12:47:00.48-0400 [STG/0]      OUT -------> Buildpack version 4.3.42
2017-10-12T12:47:01.55-0400 [STG/0]      OUT Installing HTTPD
2017-10-12T12:47:01.55-0400 [STG/0]      OUT HTTPD 2.4.27
2017-10-12T12:47:22.25-0400 [STG/0]      ERR Traceback (most recent call last):
2017-10-12T12:47:22.25-0400 [STG/0]      ERR   File "/tmp/buildpacks/53afeee42ed33310d0cfc933daa21170/scripts/compile.py", line 55, in <module>
2017-10-12T12:47:22.25-0400 [STG/0]      ERR     .from_build_pack('lib/additional_commands')
2017-10-12T12:47:22.25-0400 [STG/0]      ERR   File "/tmp/buildpacks/53afeee42ed33310d0cfc933daa21170/lib/build_pack_utils/builder.py", line 209, in extensions
2017-10-12T12:47:22.25-0400 [STG/0]      ERR     process_extension(path, ctx, 'compile', process, args=[self])
2017-10-12T12:47:22.25-0400 [STG/0]      ERR   File "/tmp/buildpacks/53afeee42ed33310d0cfc933daa21170/lib/build_pack_utils/utils.py", line 69, in process_extension
2017-10-12T12:47:22.25-0400 [STG/0]      ERR     success(getattr(extn, to_call)(*args))
2017-10-12T12:47:22.25-0400 [STG/0]      ERR   File "/tmp/buildpacks/53afeee42ed33310d0cfc933daa21170/lib/httpd/extension.py", line 45, in compile
2017-10-12T12:47:22.25-0400 [STG/0]      ERR     .package('HTTPD')
2017-10-12T12:47:22.25-0400 [STG/0]      ERR   File "/tmp/buildpacks/53afeee42ed33310d0cfc933daa21170/lib/build_pack_utils/builder.py", line 185, in package
2017-10-12T12:47:22.25-0400 [STG/0]      ERR     self._installer.install_binary(key)
2017-10-12T12:47:22.25-0400 [STG/0]      ERR   File "/tmp/buildpacks/53afeee42ed33310d0cfc933daa21170/lib/build_pack_utils/cloudfoundry.py", line 214, in install_binary
2017-10-12T12:47:22.25-0400 [STG/0]      ERR     strip=strip)
2017-10-12T12:47:22.25-0400 [STG/0]      ERR   File "/tmp/buildpacks/53afeee42ed33310d0cfc933daa21170/lib/build_pack_utils/cloudfoundry.py", line 190, in _install_binary_from_manifest
2017-10-12T12:47:22.25-0400 [STG/0]      ERR     self._dwn.download(url, self._ctx['TMPDIR'])
2017-10-12T12:47:22.25-0400 [STG/0]      ERR   File "/tmp/buildpacks/53afeee42ed33310d0cfc933daa21170/lib/build_pack_utils/downloads.py", line 40, in download
2017-10-12T12:47:22.25-0400 [STG/0]      ERR     raise RuntimeError("MD5 of downloaded dependency does not match expected value")
2017-10-12T12:47:22.25-0400 [STG/0]      ERR RuntimeError: MD5 of downloaded dependency does not match expected value
2017-10-12T12:47:22.26-0400 [STG/0]      ERR Failed to compile droplet: Failed to run finalize script: exit status 1
2017-10-12T12:47:22.27-0400 [STG/0]      OUT Exit status 223
2017-10-12T12:47:22.60-0400 [STG/0]      OUT Stopping instance 55200881-865a-4651-bd2e-2844167d01cf
2017-10-12T12:47:22.60-0400 [STG/0]      OUT Destroying container
2017-10-12T12:47:22.90-0400 [STG/0]      OUT Successfully destroyed container

```

I am not using proxy and the manual download of file works without any issue.
The environment was created using following command -

```
bosh create-env ~/bosh-deployment/bosh-deployment/bosh.yml   \
  --state ./state.json  \
  -o ~/bosh-deployment/bosh-deployment/virtualbox/cpi.yml  \
  -o ~/bosh-deployment/bosh-deployment/virtualbox/outbound-network.yml   \
  -o ~/bosh-deployment/bosh-deployment/bosh-lite.yml   \
  -o ~/bosh-deployment/bosh-deployment/bosh-lite-runc.yml   \
  -o ~/bosh-deployment/bosh-deployment/jumpbox-user.yml   \
  --vars-store ./creds.yml   \
  -v director_name="Bosh Lite Director"   \
  -v internal_ip=192.168.50.6   \
  -v internal_gw=192.168.50.1   \
  -v internal_cidr=192.168.50.0/24   \
  -v outbound_network_name=Nat2Network
```

I suspect there is some sort of routing / translate issue.

Thanks.

**Comment by dsabeti** [comment]
Hi @fadedreamz 

Could you be more specific about what you mean when you say
> (it also failed to download the packages for deployement)
Do you mean that running `bosh deploy` failed? Could you provide the error message?

Also, can you download the file by hand if you ssh onto the bosh director? How about if you ssh into one of the jobs (for example, if you were to `bosh ssh diego-cell`)?

**Comment by fadedreamz** [comment]
Hi @dsabeti
Yes, bosh deploy fails. It just starts the download for capi and then fails. So, I downloaded them manually (wget) and replaced the path into the deployment yml.

Is jumpbox ssh is the same as ssh into director?
I will try to check the manual download into the jobs and update you asap.
Thanks!

**Comment by fadedreamz** [comment]
@dsabeti 
It appears that it cannot resolve the hostname - following is the log 

> diego-cell/3fea3263-8113-4121-ae75-da46c3182a80:/tmp$ wget https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.163.0
> --2017-10-14 23:38:50--  https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.163.0
> Resolving bosh.io (bosh.io)... failed: Name or service not known.
> wget: unable to resolve host address ‘bosh.io’
> diego-cell/3fea3263-8113-4121-ae75-da46c3182a80:/tmp$

Regards

**Comment by dsabeti** [comment]
Ok, let's get some help from the BOSH team, since this seems to be an issue with your bosh-lite setup, rather than a cf-deployment issue.

@cppforlife @dpb587, could someone from the bosh team help out with this some time this week?

**Comment by dpb587-pivotal** [comment]
@fadedreamz this sounds like DNS may be misconfigured in your environment. If you `bosh ssh` back on onto the diego-cell, can you see what DNS resolvers are configured in `/etc/resolv.conf`, and verify connectivity+DNS queries directly to those servers? If using consul, you could also verify which recursors are configured in your deployment (perhaps the recursors are not accessible from your environment).

**Comment by dsabeti** [comment]
Hi @fadedreamz, any updates?

**Comment by fadedreamz** [comment]
@dpb587-pivotal  and @dsabeti  
sorry for the late reply, was busy with something else.
It seems the primary nameserver is setup to 127.0.0.1 which is failing to resolve the name.
I believe we need internal dns server for locating the other vms?

logs follows -
```
diego-cell/3fea3263-8113-4121-ae75-da46c3182a80:~$ cat /etc/resolv.conf 
nameserver 127.0.0.1
nameserver 8.8.8.8
diego-cell/3fea3263-8113-4121-ae75-da46c3182a80:~$ nslookup google.com
;; Got SERVFAIL reply from 127.0.0.1, trying next server
;; connection timed out; no servers could be reached
```

regards

**Comment by dpb587-pivotal** [comment]
@fadedreamz, I think you'll find consul on those VMs, which should be listening on 127.0.0.1 to answer those queries. Sounds like either consul may not be using the correct DNS servers, or outbound network access may not be working in general. Would be worth trying to `ping 8.8.8.8` (using an IP instead of a DNS) to verify connectivity from the cell.

**Comment by fadedreamz** [comment]
@dpb587-pivotal  bosh -e vbox -d cf vms gives following output - (consul is there)
> api/e73215e5-46ee-42a1-bfae-b42aeb1845f5               running        z1  10.244.0.135  54e0b537-dcac-4a47-6f12-39bd06c17bea  small  
> blobstore/a4071524-eca9-480b-ab77-73079d70ecc4         running        z1  10.244.0.134  81b9f208-0cf9-4d68-7203-b2af0c5faecb  small  
> cc-worker/488231da-4a03-4622-9062-5c03e62d0da3         running        z1  10.244.0.136  6b4f5f85-96a8-4b07-7b9e-a3988273bc49  minimal  
> consul/be8f0aec-f0cd-443c-afb7-805cfb323e56            running        z1  10.244.0.128  b0e431af-7826-44f0-5e03-f857b982fbbe  minimal  
> diego-api/1ccd4365-c628-4b67-b4de-f524d6a7cfaa         running        z1  10.244.0.132  5a9cd7fc-9527-499a-49f3-4be36d5d3a37  small  
> diego-cell/3fea3263-8113-4121-ae75-da46c3182a80        running        z1  10.244.0.139  7ce4afb9-3cb5-4821-4bc0-91443a15cd3a  small-highmem  
> doppler/36af892e-6069-477d-9207-cdce8800b587           running        z1  10.244.0.130  87264e1b-5c70-4f7e-6876-398b7cdbe574  minimal  
> log-api/2dae2656-c529-4ee9-ba65-80d9e8074a3b           running        z1  10.244.0.140  1e50adec-7354-4876-652c-6a11750ab402  sharedcpu  
> mysql/75dbc8ca-f0b9-4ab3-8d2c-1199868cae45             running        z1  10.244.0.131  92dae441-f279-4654-7a3f-87163d03efce  small  
> nats/0abf6c10-1ffe-47df-81e0-c5969dcab025              running        z1  10.244.0.129  39d38a63-9f03-433b-738a-b1bf09873bf6  minimal  
> router/ac90486b-d04c-4190-9425-49083a6b2069            running        z1  10.244.0.34   808601b4-dcff-419e-7a3d-6efff271a584  minimal  
> scheduler/c72fb6e3-665f-4b63-9a2f-4460502e700c         running        z1  10.244.0.138  b26c2681-b957-47e8-739d-617d5950523d  minimal  
> syslog-scheduler/19897af1-469b-4823-8019-785c05a2adc8  running        z1  10.244.0.141  495aa260-80e5-406b-6df7-a206f2ed3151  minimal  
> tcp-router/a4e6a938-f3f9-43c9-969f-a58a59ef524f        running        z1  10.244.0.137  673ce555-652e-4a88-4936-67349735915a  minimal  
> uaa/71b5cd94-2d98-4cd6-8624-d6d1940d0e29               running        z1  10.244.0.133  42fef0c3-9e0c-4076-42f6-cafc20f08f4e  minimal 

I mentioned early that I can download the package manually from the system and put it there to make it work (for example, clone the buildpack, built it locally and then push it under a different name. At the time of deployment just use custom buildpack and it works).
I had previous cloud foundry deployed on the system (cf-dev) and it was working perfectly, but I had to upgrade as I believe the old one automatically broke due to dns name changes (I suspect, it was unable to deploy application anymore).

**Comment by dsabeti** [comment]
Hi @fadedreamz, I noticed that this issue hasn't been updated in a while. Are you still experiencing this issue?

**Comment by fadedreamz** [comment]
Yes, the issue is still there, but you can close it because no one actually
provided the solution. My guess is that, one may have to take the long road
like I did.

Regards and thanks
