### ISSUE TITLE
CF Deployment - "SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by kenlimitless** [cloudfoundry/cf-deployment#409]
Hi, 

Faced the following errors when trying to deploy CloudFoundry after BOSH Lite, tried to look through the issues page before opening this new issue. Any guidance much appreciated!

XXX:~/workspace/cf-deployment$ bosh -e vbox -d cf deploy ~/workspace/cf-deployment/cf-deployment.yml -o ~/workspace/cf-deployment/operations/use-compiled-releases.yml -o ~/workspace/cf-deployment/operations/bosh-lite.yml --vars-store ~/deployments/vbox/deployment-vars.yml -v system_domain=bosh-lite.com
Using environment '192.168.50.6' as client 'admin'

Using deployment 'cf'

Task 60
Task 61
Task 63
Task 64
Task 62
Task 61 | 17:09:56 | Downloading remote release: Downloading remote release
Task 60 | 17:09:56 | Downloading remote release: Downloading remote release
Task 62 | 17:09:56 | Downloading remote release: Downloading remote release
Task 61 | 17:10:01 | Downloading remote release: Downloading remote release (00:00:05)
                   L Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
Task 61 | 17:10:01 | Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Task 61 Started  Fri Feb 16 17:09:56 UTC 2018
Task 61 Finished Fri Feb 16 17:10:01 UTC 2018
Task 61 Duration 00:00:05
Task 61 error

Task 60 | 17:10:01 | Downloading remote release: Downloading remote release (00:00:05)
                   L Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
Task 60 | 17:10:01 | Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Task 60 Started  Fri Feb 16 17:09:56 UTC 2018
Task 60 Finished Fri Feb 16 17:10:01 UTC 2018
Task 60 Duration 00:00:05
Task 60 error

Task 64 | 17:10:01 | Downloading remote release: Downloading remote release
Task 63 | 17:10:01 | Downloading remote release: Downloading remote release
Task 62 | 17:10:02 | Downloading remote release: Downloading remote release (00:00:06)
                   L Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
Task 62 | 17:10:02 | Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Task 62 Started  Fri Feb 16 17:09:56 UTC 2018
Task 62 Finished Fri Feb 16 17:10:02 UTC 2018
Task 62 Duration 00:00:06
Task 62 error

Task 64 | 17:10:07 | Downloading remote release: Downloading remote release (00:00:06)
                   L Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
Task 64 | 17:10:07 | Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Task 64 Started  Fri Feb 16 17:10:01 UTC 2018
Task 64 Finished Fri Feb 16 17:10:07 UTC 2018
Task 64 Duration 00:00:06
Task 64 error

Task 63 | 17:10:07 | Downloading remote release: Downloading remote release (00:00:06)
                   L Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
Task 63 | 17:10:07 | Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Task 63 Started  Fri Feb 16 17:10:01 UTC 2018
Task 63 Finished Fri Feb 16 17:10:07 UTC 2018
Task 63 Duration 00:00:06
Task 63 error

Creating and uploading releases:
  - Uploading release 'binary-buildpack/1.0.16':
      Uploading remote release 'https://storage.googleapis.com/cf-deployment-compiled-releases/binary-buildpack-1.0.16-ubuntu-trusty-3541.2-20180209-185131-617665116.tgz':
        Expected task '61' to succeed but state is 'error'
  - Uploading release 'capi/1.49.0':
      Uploading remote release 'https://storage.googleapis.com/cf-deployment-compiled-releases/capi-1.49.0-ubuntu-trusty-3541.2-20180209-190000-606263545.tgz':
        Expected task '60' to succeed but state is 'error'
  - Uploading release 'cf-smoke-tests/40':
      Uploading remote release 'https://storage.googleapis.com/cf-deployment-compiled-releases/cf-smoke-tests-40-ubuntu-trusty-3541.2-20180209-185229-326531481.tgz':
        Expected task '62' to succeed but state is 'error'
  - Uploading release 'cf-networking/1.10.0':
      Uploading remote release 'https://storage.googleapis.com/cf-deployment-compiled-releases/cf-networking-1.10.0-ubuntu-trusty-3541.2-20180209-185501-9626994.tgz':
        Expected task '64' to succeed but state is 'error'
  - Uploading release 'cf-mysql/36.10.0':
      Uploading remote release 'https://storage.googleapis.com/cf-deployment-compiled-releases/cf-mysql-36.10.0-ubuntu-trusty-3541.2-20180209-192425-36125387.tgz':
        Expected task '63' to succeed but state is 'error'

Exit code 1

XXX:~/workspace/cf-deployment$ bosh task 60 --debug
Using environment '192.168.50.6' as client 'admin'

Task 60

I, [2018-02-16T17:09:56.090548 #3445] [0x2b1791d92f50]  INFO -- TaskHelper: Director Version: 264.7.0
I, [2018-02-16T17:09:56.090715 #3445] [0x2b1791d92f50]  INFO -- TaskHelper: Enqueuing task: 60
I, [2018-02-16T17:09:56 #84659] []  INFO -- DirectorJobRunner: Looking for task with task id 60
D, [2018-02-16T17:09:56 #84659] [] DEBUG -- DirectorJobRunner: (0.000662s) SELECT * FROM "tasks" WHERE "id" = 60
I, [2018-02-16T17:09:56 #84659] []  INFO -- DirectorJobRunner: Found task #<Bosh::Director::Models::Task @values={:id=>60, :state=>"processing", :timestamp=>2018-02-16 17:09:56 UTC, :description=>"create release", :result=>nil, :output=>"/var/vcap/store/director/tasks/60", :checkpoint_time=>2018-02-16 17:09:56 UTC, :type=>"update_release", :username=>"admin", :deployment_name=>nil, :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
I, [2018-02-16T17:09:56 #84659] []  INFO -- DirectorJobRunner: Running from worker 'worker_3' on director/41010d22-0d83-4a56-589e-30df8215c3de (127.0.0.1)
I, [2018-02-16T17:09:56 #84659] []  INFO -- DirectorJobRunner: Starting task: 60
I, [2018-02-16T17:09:56 #84659] [task:60]  INFO -- DirectorJobRunner: Creating job
D, [2018-02-16T17:09:56 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.001218s) SELECT * FROM "tasks" WHERE "id" = 60
D, [2018-02-16T17:09:56 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.000749s) SELECT * FROM "tasks" WHERE "id" = 60
I, [2018-02-16T17:09:56 #84659] [task:60]  INFO -- DirectorJobRunner: Performing task: #<Bosh::Director::Models::Task @values={:id=>60, :state=>"processing", :timestamp=>2018-02-16 17:09:56 UTC, :description=>"create release", :result=>nil, :output=>"/var/vcap/store/director/tasks/60", :checkpoint_time=>2018-02-16 17:09:56 UTC, :type=>"update_release", :username=>"admin", :deployment_name=>nil, :started_at=>nil, :event_output=>"", :result_output=>"", :context_id=>""}>
D, [2018-02-16T17:09:56 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.000381s) BEGIN
D, [2018-02-16T17:09:56 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.000737s) UPDATE "tasks" SET "state" = 'processing', "timestamp" = '2018-02-16 17:09:56.387564+0000', "description" = 'create release', "result" = NULL, "output" = '/var/vcap/store/director/tasks/60', "checkpoint_time" = '2018-02-16 17:09:56.387921+0000', "type" = 'update_release', "username" = 'admin', "deployment_name" = NULL, "started_at" = '2018-02-16 17:09:56.387769+0000', "event_output" = '', "result_output" = '', "context_id" = '' WHERE ("id" = 60)
D, [2018-02-16T17:09:56 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.005387s) COMMIT
I, [2018-02-16T17:09:56 #84659] [task:60]  INFO -- DirectorJobRunner: Processing update release
I, [2018-02-16T17:09:56 #84659] [task:60]  INFO -- DirectorJobRunner: Downloading remote release
D, [2018-02-16T17:09:56 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.001607s) BEGIN
D, [2018-02-16T17:09:56 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.001120s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1518800996,"stage":"Downloading remote release","tags":[],"total":1,"task":"Downloading remote release","index":1,"state":"started","progress":0}
') WHERE ("id" = 60)
D, [2018-02-16T17:09:56 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.017407s) COMMIT
I, [2018-02-16T17:09:56 #84659] [task:60]  INFO -- DirectorJobRunner: Downloading remote release from https://storage.googleapis.com/cf-deployment-compiled-releases/capi-1.49.0-ubuntu-trusty-3541.2-20180209-190000-606263545.tgz
D, [2018-02-16T17:10:01 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.000422s) BEGIN
D, [2018-02-16T17:10:01 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.000833s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1518801001,"stage":"Downloading remote release","tags":[],"total":1,"task":"Downloading remote release","index":1,"state":"failed","progress":100,"data":{"error":"SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed"}}
') WHERE ("id" = 60)
D, [2018-02-16T17:10:01 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.002437s) COMMIT
D, [2018-02-16T17:10:01 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.003813s) BEGIN
D, [2018-02-16T17:10:01 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.001620s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1518801001,"error":{"code":100,"message":"SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed"}}
') WHERE ("id" = 60)
D, [2018-02-16T17:10:01 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.005364s) COMMIT
E, [2018-02-16T17:10:01 #84659] [task:60] ERROR -- DirectorJobRunner: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:948:in `connect'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:876:in `start'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:608:in `start'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/download_helper.rb:22:in `download_remote_file'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_release.rb:67:in `download_remote_release'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_release.rb:45:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:62:in `block in single_step_stage'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:56:in `block in track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:54:in `track_and_log'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:62:in `single_step_stage'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_release.rb:45:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in `block in perform'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:83:in `block (3 levels) in run'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D, [2018-02-16T17:10:01 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.002060s) SELECT * FROM "tasks" WHERE ("id" = 60) LIMIT 1
D, [2018-02-16T17:10:01 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.008240s) BEGIN
D, [2018-02-16T17:10:01 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.000747s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2018-02-16 17:10:01.679821+0000', "description" = 'create release', "result" = 'SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed', "output" = '/var/vcap/store/director/tasks/60', "checkpoint_time" = '2018-02-16 17:09:56.387921+0000', "type" = 'update_release', "username" = 'admin', "deployment_name" = NULL, "started_at" = '2018-02-16 17:09:56.387769+0000', "event_output" = '{"time":1518800996,"stage":"Downloading remote release","tags":[],"total":1,"task":"Downloading remote release","index":1,"state":"started","progress":0}
{"time":1518801001,"stage":"Downloading remote release","tags":[],"total":1,"task":"Downloading remote release","index":1,"state":"failed","progress":100,"data":{"error":"SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed"}}
{"time":1518801001,"error":{"code":100,"message":"SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed"}}
', "result_output" = '', "context_id" = '' WHERE ("id" = 60)
D, [2018-02-16T17:10:01 #84659] [task:60] DEBUG -- DirectorJobRunner: (0.004859s) COMMIT
I, [2018-02-16T17:10:01 #84659] []  INFO -- DirectorJobRunner: Task took 5.354936172 seconds to process.

Task 60 error

Capturing task '60' output:
  Expected task '60' to succeed but state is 'error'

Exit code 1

**Comment by kenlimitless** [comment]
I believe this is due to a proxy issue from my lab, close the case for now.
