### ISSUE TITLE
Passphrase for UAA SAML key is empty ("") and UAA throws an error

### ISSUE THREAD

**Issue by phong2tran** [cloudfoundry/cf-deployment#423]
I'm not sure if this forum/project or uaa-release(https://github.com/cloudfoundry/uaa-release)/uaa(https://github.com/cloudfoundry/uaa) is more appropriate to file this issue. 

I'm in the process of upgrading to cf-deployment from cf-release and uaa instance failed to be updated:

Task 426 | 00:10:25 | Updating instance uaa: uaa/09cf12e3-4c1b-45e9-b3b8-29677e1bd52d (0) (canary) (00:05:50)
                 L Error: Action Failed get_task: Task 0f63687a-1dfc-47de-6557-6bb5036d9b16 result: 1 of 1 post-start scripts failed. Failed Jobs: uaa.

With this error found in uaa.log:
-----------------------------------
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityZoneConfigurationBootstrap' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: Invocation of init method failed; nested exception is org.cloudfoundry.identity.uaa.zone.InvalidIdentityZoneDetailsException: The zone configuration is invalid. There is a security problem with the SAML SP Key configuration for key 'key-1'.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
        ... 111 more
Caused by: org.cloudfoundry.identity.uaa.zone.InvalidIdentityZoneDetailsException: The zone configuration is invalid. There is a security problem with the SAML SP Key configuration for key 'key-1'.
        at org.cloudfoundry.identity.uaa.zone.GeneralIdentityZoneValidator.validate(GeneralIdentityZoneValidator.java:35)
        at org.cloudfoundry.identity.uaa.impl.config.IdentityZoneConfigurationBootstrap.afterPropertiesSet(IdentityZoneConfigurationBootstrap.java:136)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
        ... 122 more
Caused by: org.cloudfoundry.identity.uaa.zone.InvalidIdentityZoneConfigurationException: There is a security problem with the SAML SP Key configuration for key 'key-1'.
        at org.cloudfoundry.identity.uaa.zone.GeneralIdentityZoneConfigurationValidator.validate(GeneralIdentityZoneConfigurationValidator.java:53)
        at org.cloudfoundry.identity.uaa.zone.GeneralIdentityZoneValidator.validate(GeneralIdentityZoneValidator.java:32)
        ... 125 more
Caused by: java.security.cert.CertificateException: Failed to read private key.
        at org.cloudfoundry.identity.uaa.util.KeyWithCert.loadPrivateKey(KeyWithCert.java:105)
        at org.cloudfoundry.identity.uaa.util.KeyWithCert.<init>(KeyWithCert.java:36)
        at org.cloudfoundry.identity.uaa.zone.GeneralIdentityZoneConfigurationValidator.validate(GeneralIdentityZoneConfigurationValidator.java:47)
        ... 126 more
Caused by: org.bouncycastle.openssl.PEMException: Unable to create OpenSSL PBDKF: Could not generate secret key
        at org.bouncycastle.openssl.jcajce.PEMUtilities.getKey(Unknown Source)
        at org.bouncycastle.openssl.jcajce.PEMUtilities.getKey(Unknown Source)
        at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
        at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
        at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
        at org.cloudfoundry.identity.uaa.util.KeyWithCert.loadPrivateKey(KeyWithCert.java:95)
        ... 128 more
Caused by: java.security.spec.InvalidKeySpecException: Could not generate secret key
        at javax.crypto.SecretKeyFactory.generateSecret(SecretKeyFactory.java:347)
        ... 134 more
Caused by: java.lang.IllegalArgumentException: password empty
        at org.bouncycastle.jcajce.provider.symmetric.OpenSSLPBKDF$PBKDF.engineGenerateSecret(Unknown Source)
        at javax.crypto.SecretKeyFactory.generateSecret(SecretKeyFactory.java:336)
```

The error said the password is empty. I checked the cf-deployment.yml (https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L349-L357) and found that there is no passphrase set;

I added a Ops file to set the password as follow:
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/saml/keys/key-1/passphrase
  value: c1oudc0w

Now I got a new a error:  
---------------------------
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'identityZoneConfigurationBootstrap' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: Invocation of init method failed; nested exception is org.cloudfoundry.identity.uaa.zone.InvalidIdentityZoneDetailsException: The zone configuration is invalid. There is a security problem with the SAML SP Key configuration for key 'key-1'.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
        ... 111 more
Caused by: org.cloudfoundry.identity.uaa.zone.InvalidIdentityZoneDetailsException: The zone configuration is invalid. There is a security problem with the SAML SP Key configuration for key 'key-1'.
        at org.cloudfoundry.identity.uaa.zone.GeneralIdentityZoneValidator.validate(GeneralIdentityZoneValidator.java:35)
        at org.cloudfoundry.identity.uaa.impl.config.IdentityZoneConfigurationBootstrap.afterPropertiesSet(IdentityZoneConfigurationBootstrap.java:136)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
        ... 122 more
Caused by: org.cloudfoundry.identity.uaa.zone.InvalidIdentityZoneConfigurationException: There is a security problem with the SAML SP Key configuration for key 'key-1'.
        at org.cloudfoundry.identity.uaa.zone.GeneralIdentityZoneConfigurationValidator.validate(GeneralIdentityZoneConfigurationValidator.java:53)
        at org.cloudfoundry.identity.uaa.zone.GeneralIdentityZoneValidator.validate(GeneralIdentityZoneValidator.java:32)
        ... 125 more
Caused by: java.security.cert.CertificateException: Failed to read private key.
        at org.cloudfoundry.identity.uaa.util.KeyWithCert.loadPrivateKey(KeyWithCert.java:105)
        at org.cloudfoundry.identity.uaa.util.KeyWithCert.<init>(KeyWithCert.java:36)
        at org.cloudfoundry.identity.uaa.zone.GeneralIdentityZoneConfigurationValidator.validate(GeneralIdentityZoneConfigurationValidator.java:47)
        ... 126 more
Caused by: org.bouncycastle.openssl.EncryptionException: exception using cipher - please check password and data.
        at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
        at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
        at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
        at org.cloudfoundry.identity.uaa.util.KeyWithCert.loadPrivateKey(KeyWithCert.java:95)
        ... 128 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
        at javax.crypto.Cipher.doFinal(Cipher.java:2165)
        ... 132 more
```

The error suggests that the password is not correct and I need to I check the password.

 Is the passphrase is needed for the UAA SAML key? If yes, why the passphrase property is not parameterized with a variable for configuration?

What could could be wrong here even the passphrase is configured with a value?

I'm using cf-deployment v1.15 and uaa release 55.

**Comment by phong2tran** [comment]
When I tired to use 'password' for passhrase and ran the deployment again. Now uaa instance is successfully updated.
Ops File:
---------
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/saml/keys/key-1/passphrase
  value: password

I'm not sure why password is ok for the passphrase but not c1oudc0w.

**Comment by dsabeti** [comment]
We discussed this offline, but it's worth capturing a summary of that conversation here.

The passphrase provided to the manifest must match that passphrase used when the SAML key was generated in the first place. cf-deployment [assumes a blank passphrase](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L357) by default. If operators believe that a non-empty passphrase would be helpful for them, we could potentially provide an ops-file for overriding it.
