### ISSUE TITLE
Getting an error: Can't generate network settings without an IP

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/cf-deployment#599]
### What is this issue about?

Get an error `Error: Can't generate network settings without an IP` when deploying cf using cf-deployment v3.4.0.

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

v3.4.0

### Please include the `bosh deploy...` command, including all the operations files:

```
bosh -n -d cf deploy ~/cf-deployment.yml \
  --vars-store=~/cf-deployment-vars.yml \
  -o ~/azure.yml \
  -o ~/scale-to-one-az.yml \
  -v system_domain=xxx.xxx.xxx.xxx.xip.io
```

### Please provide output that helps describe the issue:

Task log:
```
+ manifest_version: v3.4.0

+ name: cf
Task 35

Task 35 | 05:45:20 | Preparing deployment: Preparing deployment (00:00:07)
                   L Error: Can't generate network settings without an IP
Task 35 | 05:45:27 | Error: Can't generate network settings without an IP

Task 35 Started  Tue Aug 21 05:45:20 UTC 2018
Task 35 Finished Tue Aug 21 05:45:27 UTC 2018
Task 35 Duration 00:00:07
Task 35 error

Updating deployment:
  Expected task '35' to succeed but state is 'error'

Exit code 1
```

Task debug log:
```
E, [2018-08-21T05:37:14.128743 #44680] [task:33] ERROR -- DirectorJobRunner: Can't generate network settings without an IP
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/manual_network.rb:43:in `network_settings'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/network_settings.rb:25:in `block in to_hash'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/network_settings.rb:23:in `each'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/network_settings.rb:23:in `to_hash'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/network_settings.rb:52:in `network_address'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/instance_plan.rb:282:in `network_address'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/links/link.rb:33:in `block in spec'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/links/link.rb:24:in `map'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/links/link.rb:24:in `spec'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/links/links_manager.rb:300:in `block (2 levels) in update_provider_intents_contents'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/links/links_manager.rb:293:in `each'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/links/links_manager.rb:293:in `block in update_provider_intents_contents'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/links/links_manager.rb:291:in `each'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/links/links_manager.rb:291:in `update_provider_intents_contents'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/assembler.rb:160:in `bind_links'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/assembler.rb:96:in `bind_models'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:90:in `block (2 levels) in perform'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/event_log.rb:105:in `advance_and_track'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:79:in `block in perform'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:13:in `block in with_deployment_lock'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/lock.rb:79:in `lock'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/lock_helper.rb:13:in `with_deployment_lock'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/update_deployment.rb:58:in `perform'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:99:in `perform_job'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `block in run'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_formatter.rb:52:in `with_thread_name'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/job_runner.rb:34:in `run'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/base_job.rb:10:in `perform'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:36:in `block in perform'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/jobs/db_job.rb:83:in `block (3 levels) in run'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
/var/vcap/data/packages/director/c9f97a90a6505a145c662e0e8a90ec81013362a5/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

### What IaaS is this issue occurring on?

azure

**Comment by bingosummer** [comment]
Duplicated of https://github.com/cloudfoundry/bosh/issues/2033
