### ISSUE TITLE
Node Application failed to start in Cloud Foundry

### ISSUE THREAD

**Issue by AnkitNode** [cloudfoundry/cf-deployment#828]
Please find the below command to push the code :
"**cf push splunk-Analyser2 -m 1G -k 500M --no-manifest -c "npm start" -b nodejs_buildpack**"
My code is being deployed but it failing to start 

- I have node Json server and React (Client) in local its working fine but while deploying in CLI its failing.
### **ERROR is highlighted in below logs**
019-10-03T22:21:30.014+05:30 [CELL/0] [OUT] Cell 9ff53b3d-64ee-485c-b4f5-dcd3da886cf1 successfully destroyed container for instance 0aa58ff3-7347-45cb-42d1-23c6
2019-10-03T22:37:39.914+05:30 [CELL/0] [OUT] Cell f94b3eb7-9622-4ef4-86b8-3965b4e18e38 creating container for instance 136c1219-4190-4761-78f2-cd76
2019-10-03T22:37:40.532+05:30 [CELL/0] [OUT] Cell f94b3eb7-9622-4ef4-86b8-3965b4e18e38 successfully created container for instance 136c1219-4190-4761-78f2-cd76
2019-10-03T22:37:45.098+05:30 [CELL/0] [OUT] Starting health monitoring of container
2019-10-03T22:37:45.778+05:30 [APP/PROC/WEB/0] [OUT] > demo-app@0.1.0 start /home/vcap/app
2019-10-03T22:37:45.778+05:30 [APP/PROC/WEB/0] [OUT] > run-p start:dev start:api
2019-10-03T22:37:46.534+05:30 [APP/PROC/WEB/0] [OUT] > demo-app@0.1.0 start:dev /home/vcap/app
2019-10-03T22:37:46.534+05:30 [APP/PROC/WEB/0] [OUT] > cross-env REACT_APP_API_URL=https://#$%$%$%$%$%:443 react-scripts start
2019-10-03T22:37:46.538+05:30 [APP/PROC/WEB/0] [OUT] > demo-app@0.1.0 prestart:api /home/vcap/app
2019-10-03T22:37:46.538+05:30 [APP/PROC/WEB/0] [OUT] > node tools/createMockDb.js
2019-10-03T22:37:46.625+05:30 [APP/PROC/WEB/0] [OUT] Mock DB created.
2019-10-03T22:37:46.633+05:30 [APP/PROC/WEB/0] [OUT] > demo-app@0.1.0 start:api /home/vcap/app
2019-10-03T22:37:46.633+05:30 [APP/PROC/WEB/0] [OUT] > node tools/apiServer.js
2019-10-03T22:37:46.959+05:30 [APP/PROC/WEB/0] [OUT] JSON Server is running on port 3001
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] /home/vcap/app/node_modules/react-dev-utils/WebpackDevServerUtils.js:166
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] compiler.hooks.done.tap('done', async stats => {
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] ^^^^^
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] SyntaxError: missing ) after argument list
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] at createScript (vm.js:56:10)
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] at Object.runInThisContext (vm.js:97:10)
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] at Module._compile (module.js:549:28)
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] at Object.Module._extensions..js (module.js:586:10)
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] at Module.load (module.js:494:32)
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] at tryModuleLoad (module.js:453:12)
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] at Function.Module._load (module.js:445:3)
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] at Module.require (module.js:504:17)
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] at require (internal/module.js:20:19)
2019-10-03T22:37:47.970+05:30 [APP/PROC/WEB/0] [ERR] at Object.<anonymous> (/home/vcap/app/node_modules/react-scripts/scripts/start.js:45:5)
2019-10-03T22:37:47.991+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Linux 4.4.0-148-generic
2019-10-03T22:37:47.991+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! argv "/home/vcap/deps/0/node/bin/node" "/home/vcap/deps/0/node/lib/node_modules/npm/bin/npm-cli.js" "run" "start:dev"
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! node v6.17.0
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! npm v3.10.10
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! code ELIFECYCLE
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm **ERR! demo-app@0.1.0 start:dev: `cross-env REACT_APP_API_URL=https://#$%$%$%$%$%:443 react-scripts start`**
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Exit status 1
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR!
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! **Failed at the demo-app@0.1.0 start:dev script 'cross-env REACT_APP_API_URL=https://#$%$%$%$%$%:443 react-scripts start'.**
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Make sure you have the latest version of node.js and npm installed.
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! If you do, this is most likely a problem with the demo-app package,
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! not with npm itself.
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Tell the author that this fails on your system:
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! cross-env REACT_APP_API_URL=https://#$%$%$%$%$%:443 react-scripts start
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! You can get information on how to open an issue for this project with:
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! npm bugs demo-app
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Or if that isn't available, you can get their info via:
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! npm owner ls demo-app
2019-10-03T22:37:47.992+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! There is likely additional logging output above.
2019-10-03T22:37:47.995+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Please include the following file with any support request:
2019-10-03T22:37:47.995+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! /home/vcap/app/npm-debug.log
2019-10-03T22:37:48.020+05:30 [APP/PROC/WEB/0] [ERR] ERROR: **"start:dev" exited with 1.**
2019-10-03T22:37:48.034+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Linux 4.4.0-148-generic
2019-10-03T22:37:48.034+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! argv "/home/vcap/deps/0/node/bin/node" "/home/vcap/deps/0/bin/npm" "start"
2019-10-03T22:37:48.034+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! node v6.17.0
2019-10-03T22:37:48.034+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! npm v3.10.10
2019-10-03T22:37:48.034+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! code ELIFECYCLE
2019-10-03T22:37:48.034+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! demo-app@0.1.0 start: `run-p start:dev start:api`
2019-10-03T22:37:48.034+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Exit status 1
2019-10-03T22:37:48.034+05:30 [APP/PROC/WEB/0] [ERR] npm ERR!
2019-10-03T22:37:48.034+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! **Failed at the demo-app@0.1.0 start script 'run-p start:dev start:api'.**
2019-10-03T22:37:48.034+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Make sure you have the latest version of node.js and npm installed.
2019-10-03T22:37:48.034+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! If you do, this is most likely a problem with the demo-app package,
2019-10-03T22:37:48.035+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! not with npm itself.
2019-10-03T22:37:48.035+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Tell the author that this fails on your system:
2019-10-03T22:37:48.035+05:30 [APP/PROC/WEB/0] [ERR] npm ERR**! run-p start:dev start:api**
2019-10-03T22:37:48.035+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! You can get information on how to open an issue for this project with:
2019-10-03T22:37:48.035+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! npm bugs demo-app
2019-10-03T22:37:48.035+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Or if that isn't available, you can get their info via:
2019-10-03T22:37:48.035+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! npm owner ls demo-app
2019-10-03T22:37:48.035+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! There is likely additional logging output above.
2019-10-03T22:37:48.038+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! Please include the following file with any support request:
2019-10-03T22:37:48.038+05:30 [APP/PROC/WEB/0] [ERR] npm ERR! /home/vcap/app/npm-debug.log
2019-10-03T22:37:48.052+05:30 [APP/PROC/WEB/0] [OUT] Exit status 1
2019-10-03T22:37:48.054+05:30 [CELL/SSHD/0] [OUT] Exit status 0
2019-10-03T22:37:48.064+05:30 [CELL/0] [OUT] Cell f94b3eb7-9622-4ef4-86b8-3965b4e18e38 stopping instance 136c1219-4190-4761-78f2-cd76
2019-10-03T22:37:48.064+05:30 [CELL/0] [OUT] Cell f94b3eb7-9622-4ef4-86b8-3965b4e18e38 destroying container for instance 136c1219-4190-4761-78f2-cd76
2019-10-03T22:37:48.080+05:30 [API/3] [OUT] Process has crashed with type: "web"
2019-10-03T22:37:48.090+05:30 [API/3] [OUT] **App instance exited with guid eb2acb2d-7083-4cdf-8f89-c1e59c24dcc9 payload: {"instance"=>"136c1219-4190-4761-78f2-cd76", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 1",** "crash_count"=>9, "crash_timestamp"=>1570122468059282181, "version"=>"e21846c6-0652-4a8a-944a-c89107539705"}
2019-10-03T22:37:49.879+05:30 [CELL/0] [OUT] Cell f94b3eb7-9622-4ef4-86b8-3965b4e18e38 successfully destroyed container for instance 136c1219-4190-4761-78f2-cd76

**Comment by davewalter** [comment]
Hi @AnkitNode,

This is beyond the scope of support offered for cf-deployment. You should reach out to the maintainers of the buildpack for assistance, either on [Github](https://github.com/cloudfoundry/nodejs-buildpack) or in [Slack](https://cloudfoundry.slack.com).

Sorry we can't be more help.

Regards,
Dave and @weymanf
