### ISSUE TITLE
Deployment always fails

### ISSUE THREAD

**Issue by lameventanas** [cloudfoundry/cf-deployment#862]
### What is this issue about?

Deployment always fails, every time I try it the error message is different.
1st try: 
```
Task 165 | 07:11:08 | Preparing deployment: Preparing deployment (00:01:18)
Task 165 | 07:12:26 | Preparing deployment: Rendering templates (00:00:45)
Task 165 | 07:13:17 | Preparing package compilation: Finding packages to compile (00:00:04)
Task 165 | 07:13:24 | Updating instance diego-api: diego-api/0e6775d9-2ca0-46b6-b56e-b1b97c850ac8 (0) (canary) (00:02:07)
Task 165 | 07:15:34 | Updating instance scheduler: scheduler/c54557c5-92de-4db1-a676-df952ed1fe4d (0) (canary) (00:01:57)
Task 165 | 07:17:32 | Updating instance tcp-router: tcp-router/66919166-260f-4d2f-89b6-a9e270b64d8d (0) (canary)
Task 165 | 07:17:32 | Updating instance doppler: doppler/23461344-81b2-4075-bfb5-4cd2086c7465 (0) (canary)
Task 165 | 07:19:00 | Updating instance tcp-router: tcp-router/66919166-260f-4d2f-89b6-a9e270b64d8d (0) (canary) (00:01:28)
Task 165 | 07:19:41 | Updating instance doppler: doppler/23461344-81b2-4075-bfb5-4cd2086c7465 (0) (canary) (00:02:09)
Task 165 | 07:19:41 | Updating instance log-api: log-api/6a3e9238-3c83-4ebf-8ba3-a87726ea5c2e (0) (canary) (00:02:25)
Task 165 | 07:22:06 | Updating instance credhub: credhub/a82b28dc-b3fc-42b5-9197-ca40b06c3dfe (0) (canary) (00:24:06)
                    L Error: 'credhub/a82b28dc-b3fc-42b5-9197-ca40b06c3dfe (0)' is not running after update. Review logs for failed jobs: loggregator_agent, loggr-forwarder-agent, prom_scraper
Task 165 | 07:46:13 | Error: 'credhub/a82b28dc-b3fc-42b5-9197-ca40b06c3dfe (0)' is not running after update. Review logs for failed jobs: loggregator_agent, loggr-forwarder-agent, prom_scraper

Task 165 Started  Mon Jan 27 07:11:08 UTC 2020
Task 165 Finished Mon Jan 27 07:46:13 UTC 2020
```
2nd try:
```
Task 198 | 08:07:29 | Preparing deployment: Preparing deployment (00:01:35)
Task 198 | 08:09:04 | Preparing deployment: Rendering templates (00:00:49)
Task 198 | 08:10:02 | Preparing package compilation: Finding packages to compile (00:00:05)
Task 198 | 08:10:11 | Updating instance api: api/04bcfb71-4338-46c3-961a-d2195af6bcfe (0) (canary) (00:27:22)
                    L Error: 'api/04bcfb71-4338-46c3-961a-d2195af6bcfe (0)' is not running after update. Review logs for failed jobs: file_server
Task 198 | 08:37:35 | Error: 'api/04bcfb71-4338-46c3-961a-d2195af6bcfe (0)' is not running after update. Review logs for failed jobs: file_server[CLI] 2020/01/27 08:37:37 ERROR - Updating deployment: Expected task '198' to succeed but st
ate is 'error'
```
3rd try:
```
Task 233 | 09:43:15 | Updating instance doppler: doppler/d48f2107-3891-49d4-b94e-5022f38468e0 (0) (canary) (00:05:43)
Task 233 | 09:55:37 | Updating instance diego-cell: diego-cell/6d173b32-3769-4d55-b504-132eb231f55d (0) (canary) (00:18:05)
Task 233 | 09:55:37 | Updating instance log-api: log-api/90013757-50b7-45b9-8b98-2005a16a932f (0) (canary) (00:04:08)
Task 233 | 09:59:45 | Updating instance credhub: credhub/4d51044f-706b-42fc-94ab-e49ab452aea5 (0) (canary)


 (00:23:18)
                    L Error: 'credhub/4d51044f-706b-42fc-94ab-e49ab452aea5 (0)' is not running after update. Review logs for failed jobs: loggregator_agent, loggr-forwarder-agent
Task 233 | 10:23:05 | Error: 'credhub/4d51044f-706b-42fc-94ab-e49ab452aea5 (0)' is not running after update. Review logs for failed jobs: loggregator_agent, loggr-forwarder-agent[CLI] 2020/01/27 10:23:07 ERROR - Updating deployment: Expected task '233' to succeed but state is 'error'

Updating deployment:
  Expected task '233' to succeed but state is 'error'
```

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

Git commit 6a1a4292cca658ec876f934c0f39c94be34e37a0 (2020-01-24)

### Please include the `bosh deploy...` command, including all the operations files (plus any experimental operation files you're using):

```
bosh --non-interactive -d cf deploy ~/workspace/cf-deployment/cf-deployment.yml --vars-store deployment-vars.yml -o operations/bosh-lite.yml -v system_domain=bosh-lite.com  -o operations/scale-to-one-az.yml -o operations/use-compiled-releases.yml
```

### Please provide output that helps describe the issue:

```
Task 233 | 09:37:32 | Updating instance tcp-router: tcp-router/9ef24f83-bcf8-494b-8738-4b7879443e4f (0) (canary)
Task 233 | 09:37:32 | Updating instance diego-cell: diego-cell/6d173b32-3769-4d55-b504-132eb231f55d (0) (canary)
Task 233 | 09:37:32 | Updating instance doppler: doppler/d48f2107-3891-49d4-b94e-5022f38468e0 (0) (canary)
Task 233 | 09:42:43 | Updating instance tcp-router: tcp-router/9ef24f83-bcf8-494b-8738-4b7879443e4f (0) (canary) (00:05:11)
Task 233 | 09:43:15 | Updating instance doppler: doppler/d48f2107-3891-49d4-b94e-5022f38468e0 (0) (canary) (00:05:43)
Task 233 | 09:55:37 | Updating instance diego-cell: diego-cell/6d173b32-3769-4d55-b504-132eb231f55d (0) (canary) (00:18:05)
Task 233 | 09:55:37 | Updating instance log-api: log-api/90013757-50b7-45b9-8b98-2005a16a932f (0) (canary) (00:04:08)
Task 233 | 09:59:45 | Updating instance credhub: credhub/4d51044f-706b-42fc-94ab-e49ab452aea5 (0) (canary)


 (00:23:18)
                    L Error: 'credhub/4d51044f-706b-42fc-94ab-e49ab452aea5 (0)' is not running after update. Review logs for failed jobs: loggregator_agent, loggr-forwarder-agent
Task 233 | 10:23:05 | Error: 'credhub/4d51044f-706b-42fc-94ab-e49ab452aea5 (0)' is not running after update. Review logs for failed jobs: loggregator_agent, loggr-forwarder-agent[CLI] 2020/01/27 10:23:07 ERROR - Updating d
eployment: Expected task '233' to succeed but state is 'error'

Updating deployment:
  Expected task '233' to succeed but state is 'error'

Exit code 1
```

### What IaaS is this issue occurring on?

Virtualbox & Bosh-lite

### Is there anything else unique or special about your setup?

16 GB of RAM, VirtualBox 5.2, behind a proxy

### Tag your pair, your PM, and/or team!
The suffering is just for me.

**Comment by davewalter** [comment]
Hi @lameventanas,

Have you reviewed the logs for the failing components to see what the problem might be?

Regards,
Dave

**Comment by lameventanas** [comment]
Which logs should I be looking in?
The documentation is very scarce in this regard.

**Comment by acosta11** [comment]
Hi @lameventanas 

When a deployment fails and I don't have access to cf log commands I generally review the stderr and stdout logs of the vm's running that component using bosh ssh to access the vm directly and navigate myself to the logs directory. You could also use bosh logs, but I don't always want to download everything.

For example, in the latest deploy where credhub failed, I would run `bosh ssh credhub/4d51044f-706b-42fc-94ab-e49ab452aea5` to get on one of the failed instances. When inside I would run the following commands to look at the logs of one of the failed jobs: loggregator_agent. (Logs are generally under /var/vcap/sys/log/<job that produces logs>)
```
sudo -i
cd /var/vcap/sys/log/loggregator_agent
less loggregator_agent.stderr.log
```

Regards,
Andrew and Dave

**Comment by lameventanas** [comment]
Hi @acosta11 ,
Thanks for your answer.
I tried deploying again, this time the error is:
```
Task 112 | 11:11:53 | Preparing deployment: Preparing deployment (00:01:44)
Task 112 | 11:13:37 | Preparing deployment: Rendering templates (00:00:41)
Task 112 | 11:14:24 | Preparing package compilation: Finding packages to compile (00:00:04)
Task 112 | 11:14:39 | Updating instance diego-cell: diego-cell/d63b623e-463c-4ab0-ad79-4bd62295fd80 (0) (canary)
Task 112 | 11:14:39 | Updating instance doppler: doppler/91e6c1f4-7a6c-458b-8796-739b13dc0ed9 (0) (canary) (00:01:48)
Task 112 | 11:30:01 | Updating instance diego-cell: diego-cell/d63b623e-463c-4ab0-ad79-4bd62295fd80 (0) (canary) (00:15:22)
                   L Error: Action Failed get_task: Task 43f03ca0-f5a6-4c71-62a0-6bc669b31250 result: 1 of 6 post-start scripts failed. Failed Jobs: route_emitter. Successful Jobs: silk-daemon, garden, vxlan-policy-age
nt, bosh-dns, rep.
Task 112 | 11:30:02 | Error: Action Failed get_task: Task 43f03ca0-f5a6-4c71-62a0-6bc669b31250 result: 1 of 6 post-start scripts failed. Failed Jobs: route_emitter. Successful Jobs: silk-daemon, garden, vxlan-policy-ag
ent, bosh-dns, rep.[CLI] 2020/02/06 11:30:04 ERROR - Updating deployment: Expected task '112' to succeed but state is 'error'

Updating deployment:
  Expected task '112' to succeed but state is 'error'

Exit code 1

```
/var/vcap/sys/log/route_emitter/route_emitter.stderr.log shows:
```
panic: Get https://uaa.service.cf.internal:8443/token_key: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

goroutine 1 [running]:
code.cloudfoundry.org/lager.(*logger).Fatal(0xc0000744e0, 0xcb41d3, 0x17, 0xda0d60, 0xc00017ca80, 0x0, 0x0, 0x0)
        /var/vcap/data/compile/route_emitter/src/code.cloudfoundry.org/lager/logger.go:162 +0x582
main.newUaaClient(0xdbe5e0, 0xc0000744e0, 0xc00016d890, 0xdbbbe0, 0x12e4690, 0x0, 0xdbe5e0)
        /var/vcap/data/compile/route_emitter/src/code.cloudfoundry.org/route-emitter/cmd/route-emitter/main.go:330 +0x27c
main.main()
        /var/vcap/data/compile/route_emitter/src/code.cloudfoundry.org/route-emitter/cmd/route-emitter/main.go:104 +0x2b84
panic: Get https://uaa.service.cf.internal:8443/token_key: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

goroutine 1 [running]:
code.cloudfoundry.org/lager.(*logger).Fatal(0xc000112600, 0xcb41d3, 0x17, 0xda0d60, 0xc0002fe8d0, 0x0, 0x0, 0x0)
        /var/vcap/data/compile/route_emitter/src/code.cloudfoundry.org/lager/logger.go:162 +0x582
main.newUaaClient(0xdbe5e0, 0xc000112600, 0xc0001a3890, 0xdbbbe0, 0x12e4690, 0x0, 0xdbe5e0)
        /var/vcap/data/compile/route_emitter/src/code.cloudfoundry.org/route-emitter/cmd/route-emitter/main.go:330 +0x27c
main.main()
        /var/vcap/data/compile/route_emitter/src/code.cloudfoundry.org/route-emitter/cmd/route-emitter/main.go:104 +0x2b84
panic: Get https://uaa.service.cf.internal:8443/token_key: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

goroutine 1 [running]:
code.cloudfoundry.org/lager.(*logger).Fatal(0xc0000b2900, 0xcb41d3, 0x17, 0xda0d60, 0xc0001cdb60, 0x0, 0x0, 0x0)
        /var/vcap/data/compile/route_emitter/src/code.cloudfoundry.org/lager/logger.go:162 +0x582
main.newUaaClient(0xdbe5e0, 0xc0000b2900, 0xc0001bd890, 0xdbbbe0, 0x12e4690, 0x0, 0xdbe5e0)
        /var/vcap/data/compile/route_emitter/src/code.cloudfoundry.org/route-emitter/cmd/route-emitter/main.go:330 +0x27c
main.main()
        /var/vcap/data/compile/route_emitter/src/code.cloudfoundry.org/route-emitter/cmd/route-emitter/main.go:104 +0x2b84
```
I can resolve uaa.service.cf.internal to 10.244.0.132, I can ping it and use wget to fetch that URL.

If I ssh to 10.244.0.132, I can see that a java process is bound to port 8443. I dig deeper and see the logs are stored in /var/vcap/sys/log/uaa.
File uaa.stderr.log shows some exceptions.
File post-start.stderr.log shows this line repeatedly:
curl: (7) Failed to connect to 127.0.0.1 port 8443: Connection refused
finally:
curl: (28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received

monit summary shows everything is running, including uaa.

Could this be a timeout due to a slow start from a java/tomcat process?
This is just a guess, but after more than 20 years of experience in this field I think "java" and "slow" are words that go together better than peanut butter and jam.

**Comment by lameventanas** [comment]
New try, I started everything from scratch.
This time I get:
```
ask 68 | 09:44:58 | Updating instance diego-cell: diego-cell/6ca11c93-4c72-4955-bc64-b6e256150e90 (0) (canary)
Task 68 | 09:50:47 | Updating instance tcp-router: tcp-router/f9011c33-a00c-4e6e-91cc-7373a7d2e787 (0) (canary) (00:05:49)
Task 68 | 09:51:21 | Updating instance doppler: doppler/e82788f7-57ed-4c50-be1e-a123d520c371 (0) (canary) (00:06:2
Task 68 | 10:05:57 | Updating instance diego-cell: diego-cell/6ca11c93-4c72-4955-bc64-b6e256150e90 (0) (canary) (00:20:59)
Task 68 | 10:05:58 | Updating instance log-api: log-api/3787a0a7-6adc-4f9e-afb3-e75f5812e194 (0) (canary) (00:02:35)
Task 68 | 10:08:33 | Updating instance credhub: credhub/e9bebc56-f32f-4826-89ae-84e4d646d627 (0) (canary) (00:22:59)
                   L Error: 'credhub/e9bebc56-f32f-4826-89ae-84e4d646d627 (0)' is not running after update. Review logs for failed jobs: loggr-forwarder-agent
Task 68 | 10:31:33 | Error: 'credhub/e9bebc56-f32f-4826-89ae-84e4d646d627 (0)' is not running after update. Review logs for failed jobs: loggr-forwarder-agent[CLI] 2020/02/07 10:31:36 ERROR - Updating deployment: Expected task '68' to succeed but state is 'error'

Updating deployment:
  Expected task '68' to succeed but state is 'error'

Exit code 1
```
I checked in the credhub VM, file /var/vcap/data/sys/log/loggr-forwarder-agent/loggr-forwarder-agent.stderr.log has this:
```
2020/02/07 10:12:24 starting forwarder-agent
FIELD NAME:                      TYPE:              ENV:                          REQUIRED:  VALUE:
Config.DownstreamIngressPortCfg  string             DOWNSTREAM_INGRESS_PORT_GLOB  false      /var/vcap/jobs/*/config/ingress_port.yml
GRPC.Port                        uint16             AGENT_PORT                    false      3458
GRPC.CAFile                      string             AGENT_CA_FILE_PATH            true       /var/vcap/jobs/loggr-forwarder-agent/config/certs/loggregator_ca.crt
GRPC.CertFile                    string             AGENT_CERT_FILE_PATH          true       /var/vcap/jobs/loggr-forwarder-agent/config/certs/forwarder.crt
GRPC.KeyFile                     string             AGENT_KEY_FILE_PATH           true       /var/vcap/jobs/loggr-forwarder-agent/config/certs/forwarder.key
GRPC.CipherSuites                []string           AGENT_CIPHER_SUITES           false      [TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384]
MetricsServer.Port               uint16             METRICS_PORT                  false      14823
MetricsServer.CAFile             string             METRICS_CA_FILE_PATH          true       /var/vcap/jobs/loggr-forwarder-agent/config/certs/metrics_ca.crt
MetricsServer.CertFile           string             METRICS_CERT_FILE_PATH        true       /var/vcap/jobs/loggr-forwarder-agent/config/certs/metrics.crt
MetricsServer.KeyFile            string             METRICS_KEY_FILE_PATH         true       /var/vcap/jobs/loggr-forwarder-agent/config/certs/metrics.key
Config.Tags                      map[string]string  AGENT_TAGS                    false      (OMITTED)
2020/02/07 10:12:24 Metrics endpoint is listening on 127.0.0.1:14823
2020/02/07 10:12:24 grpc bound to: 127.0.0.1:3458
2020/02/07 10:13:59 http: TLS handshake error from 127.0.0.1:58430: read tcp 127.0.0.1:14823->127.0.0.1:58430: i/o timeout
2020/02/07 10:14:14 http: TLS handshake error from 127.0.0.1:58814: read tcp 127.0.0.1:14823->127.0.0.1:58814: i/o timeout
2020/02/07 10:14:59 http: TLS handshake error from 127.0.0.1:60038: read tcp 127.0.0.1:14823->127.0.0.1:60038: i/o timeout
2020/02/07 10:17:29 http: TLS handshake error from 127.0.0.1:35906: read tcp 127.0.0.1:14823->127.0.0.1:35906: i/o timeout
2020/02/07 10:18:45 http: TLS handshake error from 127.0.0.1:37918: read tcp 127.0.0.1:14823->127.0.0.1:37918: i/o timeout
2020/02/07 10:20:14 http: TLS handshake error from 127.0.0.1:40336: read tcp 127.0.0.1:14823->127.0.0.1:40336: i/o timeout
2020/02/07 10:22:44 http: TLS handshake error from 127.0.0.1:44824: write tcp 127.0.0.1:14823->127.0.0.1:44824: i/o timeout
2020/02/07 10:22:59 http: TLS handshake error from 127.0.0.1:45242: read tcp 127.0.0.1:14823->127.0.0.1:45242: i/o timeout
2020/02/07 10:23:29 http: TLS handshake error from 127.0.0.1:46058: read tcp 127.0.0.1:14823->127.0.0.1:46058: i/o timeout
2020/02/07 10:25:59 http: TLS handshake error from 127.0.0.1:50108: read tcp 127.0.0.1:14823->127.0.0.1:50108: i/o timeout
2020/02/07 10:26:59 http: TLS handshake error from 127.0.0.1:51712: read tcp 127.0.0.1:14823->127.0.0.1:51712: i/o timeout
2020/02/07 10:27:14 http: TLS handshake error from 127.0.0.1:52104: read tcp 127.0.0.1:14823->127.0.0.1:52104: i/o timeout
2020/02/07 10:27:29 http: TLS handshake error from 127.0.0.1:52490: read tcp 127.0.0.1:14823->127.0.0.1:52490: i/o timeout
2020/02/07 12:08:44 http: TLS handshake error from 127.0.0.1:39050: read tcp 127.0.0.1:14823->127.0.0.1:39050: i/o timeout
```

**Comment by pivotaljohn** [comment]
@lameventanas  Sorry you're having such trouble.  The io timeouts we see in the logs leads us to believe that your BOSH Lite install has too meager of resources.

In short, it looks like you might need a larger/faster machine to run this on.
